### ISSUE TITLE
Storage key is not working

### ISSUE THREAD

**Issue by SinanErmis** [TheFe91/cached_firestorage#1]
Hello, I'm using this package in my app to retrieve user profile pictures. Apparently storage key feature is not working.

Version 1:
```dart
RemotePicture(
              imagePath: 'pp/${userId}.jpeg',
              //storageKey: 'pp',
              mapKey: userId!,
              useAvatarView: true,
              avatarViewRadius: 32,
              fit: BoxFit.cover,
            )
```

Result: It's working just fine
<img width="82" alt="Ekran Resmi 2023-11-15 16 32 16" src="https://github.com/TheFe91/cached_firestorage/assets/61187716/8bbeb7e0-0c7e-4c1d-9a1a-7701c1c2ac30">

Version 2:
```dart 
RemotePicture(
            imagePath: 'pp/${userId}.jpeg',
            storageKey: 'pp',
            mapKey: userId!,
            useAvatarView: true,
            avatarViewRadius: 32,
            fit: BoxFit.cover,
          )
```

Result: App gets stuck. When I hot restart, the result looks like this: 
<img width="63" alt="Ekran Resmi 2023-11-15 16 37 54" src="https://github.com/TheFe91/cached_firestorage/assets/61187716/5abb2385-8a07-4a59-9bb3-91c725aaae1c">

**Comment by TheFe91** [comment]
Hi there, thanks for the issue.

Have you run the `setStorageKeys` in the main of your application?

```dart
/// Sets the storage keys
void setStorageKeys(Map<String, String> keys) {
  assert(!keys.keys.contains('default'), 'The default key is automatically set');
  _storageKeys = {..._storageKeys, ...keys};
}
```

Something like

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  /* some code */

  CachedFirestorage.instance.setStorageKeys({'pp': 'pp'});
}
```

Maybe there's a lack of documentation on this point

**Comment by TheFe91** [comment]
OK, I've added some documentation and submitted v `0.1.8` on pub.
Let me know if this is clearer

**Comment by TheFe91** [comment]
Closing as no reply is coming in

**Comment by SinanErmis** [comment]
Yes, i couldn't make it work with storage key before. gonna test this version asap, I'll give feedbacks. Sorry for late reply.

I also have a question, is it possible to make RemotePicture hero compatible?

**Comment by TheFe91** [comment]
> I also have a question, is it possible to make RemotePicture hero compatible?

I can give it a try. Please open another issue as a feature request for better tracking, thank you!

**Comment by SinanErmis** [comment]
> Hi there, thanks for the issue.
> 
> Have you run the `setStorageKeys` in the main of your application?
> 
> ```dart
> /// Sets the storage keys
> void setStorageKeys(Map<String, String> keys) {
>   assert(!keys.keys.contains('default'), 'The default key is automatically set');
>   _storageKeys = {..._storageKeys, ...keys};
> }
> ```
> 
> Something like
> 
> ```dart
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   /* some code */
> 
>   CachedFirestorage.instance.setStorageKeys({'pp': 'pp'});
> }
> ```
> 
> Maybe there's a lack of documentation on this point

Btw I just saw this. I didn't even think about adding this to my code because it's not mentioned in the documentation neither in your medium article. Sorry for inconvenience, I didn't get to see any mails about this particular issue until today.
